import type { Employee } from "../types/user.interface";
import api from "./api";

export const EmployeeService = {
  getAllEmployees: async (): Promise<Employee[]> => {
    // inside get<> -> this pre-define the data type of the data returned from the fetching of server
    const employeeList = await api.get<Employee[]>(`/employees`);

    return employeeList.data;
  },

  addEmployee: async (
    // Omit: take the data Employee as payload then remove the "id" field -> this id field will be auto generated by the json db server
    employeeData: Omit<Employee, "id">,
  ): Promise<Employee> => {
    // Omit: auto omit the id of the employee, which means when the FE send the data payload, it doesn't need the id fields
    const response = await api.post<Employee>(`/employees`, employeeData);
    return response.data;
  },

  updateEmployee: async (
    id: string,
    employeeData: Omit<Employee, "id">,
  ): Promise<Employee> => {
    const response = await api.put<Employee>(`/employees/${id}`, {
      id,
      ...employeeData,
    });
    return response.data;
  },

  deleteEmployee: async (id: string): Promise<string> => {
    await api.delete(`/employees/${id}`);
    return id;
  },
};
